Marvin's --enable-server-only configure option.

diff --git a/xpilot/configure b/xpilot/configure
--- a/xpilot/configure
+++ b/xpilot/configure
@@ -311,7 +311,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT XP_AUTHORS XP_COPYRIGHTDATE XP_COPYRIGHT XP_RELEASEDATE XP_DATADIR CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE RANLIB ac_ct_RANLIB CPP X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS X_EXTENSIONS_LIB SDL_CONFIG SDL_CFLAGS SDL_LIBS SDL_EXTRA_LIBS GL_LIBS COND_SDL_CLIENT_TRUE COND_SDL_CLIENT_FALSE COND_SDL_GAMELOOP_TRUE COND_SDL_GAMELOOP_FALSE SOUND_LIBS COND_SOUND_TRUE COND_SOUND_FALSE EGREP LIBOBJS POW_LIB LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT XP_AUTHORS XP_COPYRIGHTDATE XP_COPYRIGHT XP_RELEASEDATE XP_DATADIR CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE RANLIB ac_ct_RANLIB CPP X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS X_EXTENSIONS_LIB W32_LIBS SDL_CONFIG SDL_CFLAGS SDL_LIBS SDL_EXTRA_LIBS GL_LIBS COND_SERVER_ONLY_TRUE COND_SERVER_ONLY_FALSE COND_SDL_CLIENT_TRUE COND_SDL_CLIENT_FALSE COND_SDL_GAMELOOP_TRUE COND_SDL_GAMELOOP_FALSE SOUND_LIBS COND_SOUND_TRUE COND_SOUND_FALSE EGREP LIBOBJS POW_LIB LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -863,6 +863,7 @@ Optional Features:
   --enable-dbe            support for X Doublebuffer Extension in client
   --enable-mbx            support for X Multibuffer Extension in client
   --enable-plockserver    lock the xpilot-ng server into memory
+  --enable-server-only    build only the server
   --enable-development    enable development code
   --enable-newsched       enable new server scheduling most useful on Linux
                           2.6
@@ -1934,6 +1935,18 @@ if test "${enable_plockserver+set}" = set; then
 
 cat >>confdefs.h <<\_ACEOF
 #define PLOCKSERVER 1
+_ACEOF
+
+fi
+fi;
+
+# Check whether --enable-server_only or --disable-server_only was given.
+if test "${enable_server_only+set}" = set; then
+  enableval="$enable_server_only"
+  if test x$enable_server_only = xyes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define SERVER_ONLY 1
 _ACEOF
 
 fi
@@ -5387,28 +5400,53 @@ fi
 
 case "$target" in
     *-*-mingw32*)
-        MATHLIB=""
-        SYS_GL_LIBS="-lopengl32 -lglu32"
-        ;;
+	MATHLIB=""
+	SYS_GL_LIBS="-lopengl32 -lglu32"
+	windows_target=yes
+	;;
     *-*-beos*)
-        MATHLIB=""
-        SYS_GL_LIBS="-lGL"
-        ;;
+	MATHLIB=""
+	SYS_GL_LIBS="-lGL"
+	;;
     *-*-linux*)
-        MATHLIB="-lm"
-        SYS_GL_LIBS="-L/usr/X11R6/lib -lGL -lGLU"
-        ;;
+	MATHLIB="-lm"
+	SYS_GL_LIBS="-L/usr/X11R6/lib -lGL -lGLU"
+	;;
     *-*-freebsd*)
-        MATHLIB="-lm"
-        SYS_GL_LIBS="-L/usr/X11R6/lib -lGL -lGLU"
+	MATHLIB="-lm"
+	SYS_GL_LIBS="-L/usr/X11R6/lib -lGL -lGLU"
 	CPPFLAGS="$CPPFLAGS -I/usr/X11R6/include -I/usr/local/include"
 	LDFLAGS="$LDFLAGS -L/usr/local/lib"
-        ;;
+	;;
     *)
-        MATHLIB="-lm"
-        SYS_GL_LIBS="-lGL -lGLU"
-        ;;
+	MATHLIB="-lm"
+	SYS_GL_LIBS="-lGL -lGLU"
+	;;
 esac
+
+if test x$windows_target = xyes; then
+	W32_LIBS="-lmingw32 -lwsock32"
+
+
+cat >>confdefs.h <<\_ACEOF
+#define _WINDOWS 1
+_ACEOF
+
+
+	enable_newsched=yes
+
+cat >>confdefs.h <<\_ACEOF
+#define NEWSCHED 1
+_ACEOF
+
+
+	enable_server_only=yes
+
+cat >>confdefs.h <<\_ACEOF
+#define SERVER_ONLY 1
+_ACEOF
+
+fi
 
 if test x$enable_sdl_client = xyes; then
 
@@ -5909,6 +5947,16 @@ echo "$as_me: error: *** Unable to find OpenGL headers and libraries!" >&2;}
    { (exit 1); exit 1; }; }
 	fi
 
+fi
+
+
+
+if test x$enable_server_only = xyes; then
+  COND_SERVER_ONLY_TRUE=
+  COND_SERVER_ONLY_FALSE='#'
+else
+  COND_SERVER_ONLY_TRUE='#'
+  COND_SERVER_ONLY_FALSE=
 fi
 
 
@@ -8727,6 +8775,13 @@ echo "$as_me: error: conditional \"am__fastdepCC\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${COND_SERVER_ONLY_TRUE}" && test -z "${COND_SERVER_ONLY_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"COND_SERVER_ONLY\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"COND_SERVER_ONLY\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${COND_SDL_CLIENT_TRUE}" && test -z "${COND_SDL_CLIENT_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"COND_SDL_CLIENT\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -9368,11 +9423,14 @@ s,@X_PRE_LIBS@,$X_PRE_LIBS,;t t
 s,@X_LIBS@,$X_LIBS,;t t
 s,@X_EXTRA_LIBS@,$X_EXTRA_LIBS,;t t
 s,@X_EXTENSIONS_LIB@,$X_EXTENSIONS_LIB,;t t
+s,@W32_LIBS@,$W32_LIBS,;t t
 s,@SDL_CONFIG@,$SDL_CONFIG,;t t
 s,@SDL_CFLAGS@,$SDL_CFLAGS,;t t
 s,@SDL_LIBS@,$SDL_LIBS,;t t
 s,@SDL_EXTRA_LIBS@,$SDL_EXTRA_LIBS,;t t
 s,@GL_LIBS@,$GL_LIBS,;t t
+s,@COND_SERVER_ONLY_TRUE@,$COND_SERVER_ONLY_TRUE,;t t
+s,@COND_SERVER_ONLY_FALSE@,$COND_SERVER_ONLY_FALSE,;t t
 s,@COND_SDL_CLIENT_TRUE@,$COND_SDL_CLIENT_TRUE,;t t
 s,@COND_SDL_CLIENT_FALSE@,$COND_SDL_CLIENT_FALSE,;t t
 s,@COND_SDL_GAMELOOP_TRUE@,$COND_SDL_GAMELOOP_TRUE,;t t
