Configure changed so that if SDL is not found, SDL client will not be compiled, also SDL_ttf and OpenGL will be looked for only if SDL is found.

diff --git a/xpilot/configure b/xpilot/configure
--- a/xpilot/configure
+++ b/xpilot/configure
@@ -311,7 +311,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT XP_AUTHORS XP_COPYRIGHTDATE XP_COPYRIGHT XP_RELEASEDATE XP_INSTLIBDIR XP_TITLE XP_WINVERSION XP_VERSION_WINDOWS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE RANLIB ac_ct_RANLIB CPP X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS SDL_CONFIG SDL_CFLAGS SDL_LIBS GL_LIBS SDL_EXTRA_LIBS EGREP LIBOBJS POW_LIB LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT XP_AUTHORS XP_COPYRIGHTDATE XP_COPYRIGHT XP_RELEASEDATE XP_INSTLIBDIR XP_TITLE XP_WINVERSION XP_VERSION_WINDOWS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE RANLIB ac_ct_RANLIB CPP X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS SDL_CONFIG SDL_CFLAGS SDL_LIBS COND_NO_SDL_TRUE COND_NO_SDL_FALSE SDL_EXTRA_LIBS GL_LIBS EGREP LIBOBJS POW_LIB LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1869,7 +1869,6 @@ fi
 
 
           ac_config_headers="$ac_config_headers config.h"
-
 
 
 XP_AUTHORS="Bjørn Stabell, Ken Ronny Schouten, Bert Gijsbers, Dick Balaska, Uoti Urpala, Juha Lindström, Kristian Söderblom and Erik Andersson"
@@ -5375,18 +5374,35 @@ echo "$as_me: WARNING: *** SDL version $SDL_VERSION not found!" >&2;}
 
 CFLAGS="$CFLAGS $SDL_CFLAGS"
 
-echo "$as_me:$LINENO: checking for OpenGL support" >&5
-echo $ECHO_N "checking for OpenGL support... $ECHO_C" >&6
-have_opengl=no
-cat >conftest.$ac_ext <<_ACEOF
+if test x$no_sdl = xyes; then
+    { echo "$as_me:$LINENO: WARNING: SDL client will not be built." >&5
+echo "$as_me: WARNING: SDL client will not be built." >&2;}
+fi
+
+
+if test "$no_sdl" = yes; then
+  COND_NO_SDL_TRUE=
+  COND_NO_SDL_FALSE='#'
+else
+  COND_NO_SDL_TRUE='#'
+  COND_NO_SDL_FALSE=
+fi
+
+
+if test x$no_sdl != xyes; then
+
+		echo "$as_me:$LINENO: checking for SDL_ttf" >&5
+echo $ECHO_N "checking for SDL_ttf... $ECHO_C" >&6
+	have_libsdl_ttf=no
+	cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
 
- #include <GL/gl.h>
- #include <GL/glu.h>
+	 #include "SDL.h"
+	 #include "SDL/SDL_ttf.h"
 
 int
 main ()
@@ -5419,7 +5435,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
 
-have_opengl=yes
+	have_libsdl_ttf=yes
 
 else
   echo "$as_me: failed program was:" >&5
@@ -5427,77 +5443,82 @@ sed 's/^/| /' conftest.$ac_ext >&5
 
 fi
 rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
-echo "$as_me:$LINENO: result: $have_opengl" >&5
-echo "${ECHO_T}$have_opengl" >&6
-if test x$have_opengl = xyes; then
-    GL_LIBS="$SDL_LIBS $SYS_GL_LIBS"
-else
-    { echo "$as_me:$LINENO: WARNING: Unable to find OpenGL headers and libraries" >&5
-echo "$as_me: WARNING: Unable to find OpenGL headers and libraries" >&2;}
-fi
-
-
-
-echo "$as_me:$LINENO: checking for libsdl-ttf" >&5
-echo $ECHO_N "checking for libsdl-ttf... $ECHO_C" >&6
-have_libsdl_ttf=no
-cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-
- #include "SDL.h"
- #include "SDL/SDL_ttf.h"
-
-int
-main ()
-{
-
-
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext
-if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
-  (eval $ac_compile) 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; } &&
-	 { ac_try='test -s conftest.$ac_objext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-
-have_libsdl_ttf=yes
-
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-fi
-rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
-echo "$as_me:$LINENO: result: $have_libsdl_ttf" >&5
+	echo "$as_me:$LINENO: result: $have_libsdl_ttf" >&5
 echo "${ECHO_T}$have_libsdl_ttf" >&6
-if test x$have_libsdl_ttf = xyes; then
-    SDL_EXTRA_LIBS="-lSDL_ttf"
+	if test x$have_libsdl_ttf = xyes; then
+	    SDL_EXTRA_LIBS="-lSDL_ttf"
+	else
+	    { { echo "$as_me:$LINENO: error: Unable to find SDL_ttf headers and libraries" >&5
+echo "$as_me: error: Unable to find SDL_ttf headers and libraries" >&2;}
+   { (exit 1); exit 1; }; }
+	fi
+
+
+
+		echo "$as_me:$LINENO: checking for OpenGL support" >&5
+echo $ECHO_N "checking for OpenGL support... $ECHO_C" >&6
+	have_opengl=no
+	cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+	 #include <GL/gl.h>
+	 #include <GL/glu.h>
+
+int
+main ()
+{
+
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+
+	have_opengl=yes
+
 else
-    { echo "$as_me:$LINENO: WARNING: Unable to find libsdl-ttf headers and libraries" >&5
-echo "$as_me: WARNING: Unable to find libsdl-ttf headers and libraries" >&2;}
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
 fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+	echo "$as_me:$LINENO: result: $have_opengl" >&5
+echo "${ECHO_T}$have_opengl" >&6
+	if test x$have_opengl = xyes; then
+	    GL_LIBS="$SDL_LIBS $SYS_GL_LIBS"
+	else
+	    { { echo "$as_me:$LINENO: error: Unable to find OpenGL headers and libraries" >&5
+echo "$as_me: error: Unable to find OpenGL headers and libraries" >&2;}
+   { (exit 1); exit 1; }; }
+	fi
+
+fi
+
 
 
 
@@ -8206,6 +8227,13 @@ echo "$as_me: error: conditional \"am__fastdepCC\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${COND_NO_SDL_TRUE}" && test -z "${COND_NO_SDL_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"COND_NO_SDL\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"COND_NO_SDL\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
@@ -8832,8 +8860,10 @@ s,@X_EXTRA_LIBS@,$X_EXTRA_LIBS,;t t
 s,@SDL_CONFIG@,$SDL_CONFIG,;t t
 s,@SDL_CFLAGS@,$SDL_CFLAGS,;t t
 s,@SDL_LIBS@,$SDL_LIBS,;t t
-s,@GL_LIBS@,$GL_LIBS,;t t
+s,@COND_NO_SDL_TRUE@,$COND_NO_SDL_TRUE,;t t
+s,@COND_NO_SDL_FALSE@,$COND_NO_SDL_FALSE,;t t
 s,@SDL_EXTRA_LIBS@,$SDL_EXTRA_LIBS,;t t
+s,@GL_LIBS@,$GL_LIBS,;t t
 s,@EGREP@,$EGREP,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@POW_LIB@,$POW_LIB,;t t
