Check for optional SDL image library.

diff --git a/xpilot/configure b/xpilot/configure
--- a/xpilot/configure
+++ b/xpilot/configure
@@ -5452,6 +5452,72 @@ echo "$as_me: error: Unable to find SDL_ttf headers and libraries" >&2;}
 	fi
 
 
+		echo "$as_me:$LINENO: checking for SDL_image" >&5
+echo $ECHO_N "checking for SDL_image... $ECHO_C" >&6
+	have_libsdl_image=no
+	cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+	 #include "SDL.h"
+	 #include "SDL/SDL_image.h"
+
+int
+main ()
+{
+
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+
+	have_libsdl_image=yes
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+	echo "$as_me:$LINENO: result: $have_libsdl_image" >&5
+echo "${ECHO_T}$have_libsdl_image" >&6
+	if test x$have_libsdl_image = xyes; then
+	    SDL_EXTRA_LIBS="-lSDL_image"
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_SDL_IMAGE 1
+_ACEOF
+
+	else
+	    { echo "$as_me:$LINENO: WARNING: Unable to find SDL_image headers and libraries" >&5
+echo "$as_me: WARNING: Unable to find SDL_image headers and libraries" >&2;}
+	fi
+
 
 		echo "$as_me:$LINENO: checking for OpenGL support" >&5
 echo $ECHO_N "checking for OpenGL support... $ECHO_C" >&6
